name: 'Checkout and Install SIPssert & Tests'
description: 'Checks out and installs the SIPssert & Tests repos'
inputs:
  sipssert-repo:
    description: 'SIPssert repository to checkout'
    required: false
    default: 'man1207/SIPssert'
  tests-repo:
    description: 'Tests repository to checkout'
    required: false
    default: ''
  directory:
    description: "Directory to store tests checkout"
    required: false
    default: 'tests'
runs:
  using: 'composite'
  steps:
    - name: Checkout SIPssert repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.sipssert-repo }}
        ref: feature/junit
        path: sipssert

    - name: Install SIPssert requirements
      run: |
        sudo apt update && sudo apt install -y tcpdump
        sudo chmod +s $(which tcpdump)
      shell: bash

    - name: Install SIPssert framework
      run: |
        cd sipssert
        python3 setup.py install --user clean
      shell: bash

    - name: Checkout Tests repo
      uses: actions/checkout@v4
      if: "${{ inputs.tests-repo != '' }}"
      with:
        repository: ${{ inputs.tests-repo }}
        ref: feature/junit
        path: ${{ inputs.directory }}
