name: Run OpenSIPS Conformance Tests

on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  opensips:
    uses: man1207/sipssert-opensips-tests/.github/workflows/run-tests.yml@feature/junit
